Add endpoint override for S3 alternatives
replikativ/konserve-s3 pull request #4
Opened 2024-11-04 12:49 UTC by groundedsage

This adds support for using alternative storage with S3 compatible API's.

Some offer global endpoints. However I was not able to figure out how to add that. So if "auto" is set as a region it defaults to "us-east-1". There is probably a better way to handle this.

2024-11-05 05:14 UTC, whilo commented
I see. Why do we need auto then if we could just set "us-east-1" manually? Also please document the new settings in the README instead of just the s3-spec-alt map internally so that other users can benefit from it as well.

2025-01-19 23:45 UTC, whilo requested changes
It looks good. Thanks a lot for making sure konserve works with minio etc.! Could you add this to the README so people know they can use other backends without having to dive into the code first?

2025-04-02 05:37 UTC, groundedsage commented
Done. After reviewing further, defaulting to "us-east-1" is common practice for S3-compatible services and is acceptable here.

2025-04-03 16:09 UTC, whilo commented
That looks good, thanks. Can you default just to us-east-1 without introducing auto? Auto suggests it is figuring something out on its own, which it isn't.

2025-04-04 06:23 UTC, groundedsage commented
Actually took another look at it again and got it working.
Most do have "auto" in the docs because they are doing something different so having the ability to align the code with that is preferred.

2025-04-04 22:59 UTC, whilo approved these changes
Thank you for adding this! :tada:

2025-04-04 22:59 UTC, merged